<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-RI7JP09I" failures="1" tests="1" name="UAT" time="27.236" errors="0" timestamp="26 Aug 2022 10:24:58 GMT">
  <testcase classname="script.ValidSignUp" name="testValidSignUp" time="13.235">
    <failure type="java.lang.AssertionError" message="Test is Failed: Recheck the entered details on sign up page again">
      <![CDATA[java.lang.AssertionError: Test is Failed: Recheck the entered details on sign up page again
at script.ValidSignUp.testValidSignUp(ValidSignUp.java:56)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testValidSignUp -->
</testsuite> <!-- UAT -->
